# Generated by Django 5.2.16 on 2026-09-26 23:22

import apps.articles.infobox
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_slug', models.SlugField(max_length=220)),
                ('to_title', models.CharField(max_length=200)),
                ('occurrences', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['to_title'],
            },
        ),
        migrations.CreateModel(
            name='MainPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('featured', 'Featured article'), ('dyk', 'Did you know…'), ('otd', 'On this day')], db_index=True, max_length=12)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Ordering within kind.')),
                ('body_markdown', models.TextField(blank=True, help_text="Used by 'dyk' and 'otd'.")),
                ('event_year', models.IntegerField(blank=True, null=True)),
                ('event_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('event_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_slug', models.SlugField(max_length=220, unique=True)),
                ('from_title', models.CharField(help_text="Display title, for the '(Redirected from X)' line.", max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['from_slug'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Short slug used by the [^key] marker.', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('authors', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('published_on', models.CharField(blank=True, help_text="Free text: '1986', 'March 2019', 'n.d.'. Sources are irregular.", max_length=40)),
                ('accessed_on', models.DateField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, help_text='One field for ISBN / DOI / arXiv / ISSN; the renderer prefix-sniffs it.', max_length=120)),
                ('quote', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TalkMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=8000)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TalkThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.PositiveIntegerField(default=0, editable=False)),
                ('participant_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='article',
            name='backlink_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='byte_size',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='UTF-8 bytes of `content`, not characters.'),
        ),
        migrations.AddField(
            model_name='article',
            name='contributor_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='extra_categories',
            field=models.ManyToManyField(blank=True, help_text='Additional categories; the primary one stays in `category`.', related_name='secondary_articles', to='articles.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='infobox',
            field=models.JSONField(blank=True, default=dict, help_text='Side panel rows. See apps/articles/infobox.py for the schema.', validators=[apps.articles.infobox.validate_infobox]),
        ),
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='is_stub',
            field=models.BooleanField(default=False, help_text='Short article that explicitly asks for expansion.'),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_alt',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_credit',
            field=models.CharField(blank=True, help_text='Attribution line. Rendered whenever it is non-empty.', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_license',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='lead_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='page_type',
            field=models.CharField(choices=[('article', 'Article'), ('disambiguation', 'Disambiguation'), ('list', 'List')], db_index=True, default='article', max_length=16),
        ),
        migrations.AddField(
            model_name='article',
            name='protection',
            field=models.CharField(choices=[('open', 'Open — any signed-in user may edit'), ('semi', 'Semi-protected — established users only'), ('full', 'Fully protected — staff only')], default='open', max_length=12),
        ),
        migrations.AddField(
            model_name='article',
            name='revision_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.CharField(blank=True, help_text='5-12 word gloss. Powers the typeahead row and the hover card.', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='watcher_total',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="lucide-react icon name, e.g. 'atom'.", max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Manual sort key; ties fall back to name.'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent category. At most two levels deep.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='articles.category'),
        ),
        migrations.AddField(
            model_name='revision',
            name='apparatus',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of what is not a plain column: references, infobox, page_type…'),
        ),
        migrations.AddField(
            model_name='revision',
            name='byte_delta',
            field=models.IntegerField(default=0, help_text='Bytes added or removed relative to the parent revision.'),
        ),
        migrations.AddField(
            model_name='revision',
            name='byte_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revision',
            name='is_bot',
            field=models.BooleanField(default=False, help_text="The 'b' flag in Recent changes."),
        ),
        migrations.AddField(
            model_name='revision',
            name='is_minor',
            field=models.BooleanField(default=False, help_text="The 'm' flag in Recent changes."),
        ),
        migrations.AddField(
            model_name='revision',
            name='is_page_creation',
            field=models.BooleanField(default=False, help_text="The 'N' flag in Recent changes."),
        ),
        migrations.AddField(
            model_name='revision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='articles.revision'),
        ),
        migrations.AddField(
            model_name='revision',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Short machine strings: 'seed', 'revert', 'api', 'import'. Never user text."),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_published', '-updated_at'], name='article_pub_updated'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['page_type', '-updated_at'], name='article_type_updated'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='category_parent_order'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['-created_at'], name='revision_recent'),
        ),
        migrations.AddIndex(
            model_name='revision',
            index=models.Index(fields=['editor', '-created_at'], name='revision_editor_recent'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_deleted', True), _connector='OR'), name='article_deleted_at_requires_flag'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='from_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='to_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_links', to='articles.article'),
        ),
        migrations.AddField(
            model_name='mainpageblock',
            name='article',
            field=models.ForeignKey(blank=True, help_text="Required for 'featured'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_page_blocks', to='articles.article'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_redirects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redirect',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='articles.article'),
        ),
        migrations.AddField(
            model_name='reference',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='articles.article'),
        ),
        migrations.AddField(
            model_name='talkmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talk_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talkmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_talk_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talkmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='articles.talkmessage'),
        ),
        migrations.AddField(
            model_name='talkthread',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_threads', to='articles.article'),
        ),
        migrations.AddField(
            model_name='talkthread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talk_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talkmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='articles.talkthread'),
        ),
        migrations.AddField(
            model_name='watch',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='articles.article'),
        ),
        migrations.AddField(
            model_name='watch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='articlelink',
            index=models.Index(fields=['to_slug'], name='articlelink_to_slug'),
        ),
        migrations.AddIndex(
            model_name='articlelink',
            index=models.Index(fields=['to_article'], name='articlelink_to_article'),
        ),
        migrations.AddConstraint(
            model_name='articlelink',
            constraint=models.UniqueConstraint(fields=('from_article', 'to_slug'), name='uniq_articlelink_from_to'),
        ),
        migrations.AddIndex(
            model_name='mainpageblock',
            index=models.Index(fields=['kind', 'position'], name='mainpageblock_kind_pos'),
        ),
        migrations.AddConstraint(
            model_name='mainpageblock',
            constraint=models.CheckConstraint(condition=models.Q(('event_month__isnull', True), models.Q(('event_month__gte', 1), ('event_month__lte', 12)), _connector='OR'), name='mainpageblock_month_range'),
        ),
        migrations.AddConstraint(
            model_name='mainpageblock',
            constraint=models.CheckConstraint(condition=models.Q(('event_day__isnull', True), models.Q(('event_day__gte', 1), ('event_day__lte', 31)), _connector='OR'), name='mainpageblock_day_range'),
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['target'], name='redirect_target_idx'),
        ),
        migrations.AddIndex(
            model_name='reference',
            index=models.Index(fields=['article', 'order'], name='reference_article_order'),
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('article', 'key'), name='uniq_reference_article_key'),
        ),
        migrations.AddIndex(
            model_name='talkthread',
            index=models.Index(fields=['article', '-last_message_at'], name='talkthread_article_recent'),
        ),
        migrations.AddConstraint(
            model_name='talkthread',
            constraint=models.UniqueConstraint(fields=('article', 'title'), name='uniq_talkthread_article_title'),
        ),
        migrations.AddIndex(
            model_name='talkmessage',
            index=models.Index(fields=['thread', 'created_at'], name='talkmessage_thread_time'),
        ),
        migrations.AddIndex(
            model_name='talkmessage',
            index=models.Index(fields=['author', '-created_at'], name='talkmessage_author_time'),
        ),
        migrations.AddIndex(
            model_name='talkmessage',
            index=models.Index(fields=['-created_at'], name='talkmessage_recent'),
        ),
        migrations.AddConstraint(
            model_name='talkmessage',
            constraint=models.CheckConstraint(condition=models.Q(('depth__lte', 4)), name='talkmessage_depth_cap'),
        ),
        migrations.AddIndex(
            model_name='watch',
            index=models.Index(fields=['user', '-created_at'], name='watch_user_recent'),
        ),
        migrations.AddConstraint(
            model_name='watch',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='uniq_watch_user_article'),
        ),
    ]
