"""Astronomy and Space — Wikiverse seed corpus.

Part of the CC BY 4.0 licensed article corpus. See __init__.py.
"""

ARTICLES = [
    {
        "title": "Mercury (planet)",
        "category": "Astronomy and Space",
        "categories": ["Physics"],
        "short_description": "The innermost and smallest planet, with an oversized iron core",
        "summary": (
            "Mercury is the smallest planet of the Solar System and the closest to the Sun, "
            "orbiting it every 88 days. An airless, heavily cratered world, it turns three "
            "times on its axis for every two circuits of the Sun."
        ),
        "content": """**Mercury** is the innermost and smallest planet of [[The Solar System]],
completing one orbit of the Sun every 87.969 days at a mean distance of 57.9 million
kilometres.[^nasafacts] Its equatorial radius of 2,440 kilometres makes it smaller than
Ganymede and Titan, the largest moons of Jupiter and Saturn, yet its mean density of 5,429
kilograms per cubic metre is second only to Earth's — the signature of a metallic core that
fills more than half the planet's volume.[^smith2012] Mercury has no moons and no appreciable
atmosphere, only a tenuous exosphere whose surface pressure is some fourteen orders of
magnitude below Earth's.[^nasafacts]

The planet is named after the Roman messenger god, conventionally explained by the speed with
which it crosses the sky; the liquid metal [[Mercury (element)|mercury]] carries the same
name, and the other senses are collected at [[Mercury]]. Because Mercury never appears more
than about 28 degrees from the Sun, it is awkward to observe from the ground, and only two
spacecraft have reached it.

## Orbit and rotation

Mercury's orbit is the most eccentric of the eight planets, at 0.2056. Its distance from the
Sun swings between 46.0 million kilometres at perihelion and 69.8 million at aphelion, and
its speed along the orbit between 59 and 39 kilometres per second, averaging 47.36 — faster
than any other planet. The orbit is also the most steeply inclined to the ecliptic, by 7.0
degrees.[^nasafacts]

Until the mid-1960s Mercury was assumed to keep one hemisphere permanently sunlit. Radar
observations made from the Arecibo Observatory in April 1965 instead returned a rotation
period of 59 ± 5 days, incompatible with the 88-day synchronous value.[^pettengill1965]
The accepted figure is 58.646 days, precisely two-thirds of the orbital period: the planet
rotates three times for every two orbits, a 3:2 spin–orbit resonance. Numerical integrations
indicate that capture into this state was the most probable outcome of a chaotic early
evolution of the spin, connecting the planet's rotation to the behaviour studied in
[[Chaos theory]].[^correia2004]

Two consequences follow. The interval between successive sunrises — the solar day — is 175.94
Earth days, or two Mercurian years. And because the spin axis is tilted by only 0.034 degrees,
Mercury has effectively no seasons, and crater floors near the poles never receive direct
sunlight.[^nasafacts]

## The precession of the perihelion

The long axis of Mercury's orbit slowly rotates. Most of that motion follows from the
precession of Earth's equinoxes and from the pull of the other planets. In 1859 Urbain Le
Verrier reported a residue that the gravitational theory of [[Isaac Newton]] could not
account for; later analysis fixed it at roughly 43 arcseconds per century. Proposed
explanations included an undiscovered intramercurial planet, provisionally named Vulcan, and
a small departure from the inverse-square law. In November 1915 Albert Einstein derived an
advance of about 43 arcseconds per century directly from the field equations of
[[General relativity|general relativity]]; the agreement was the theory's first observational
success and remains one of its standard tests.[^will2014]

## Interior and magnetic field

Doppler tracking of the MESSENGER orbiter's radio signal yielded a gravity field consistent
with a core radius near 2,000 kilometres — about 83 per cent of the planetary radius, so that
the core fills roughly 57 per cent of the planet's volume against some 17 per cent for
Earth's.[^smith2012] Earth-based radar measurements of the planet's forced libration in
longitude, with an amplitude of about 36 arcseconds, showed that the mantle is not rigidly
locked to the deep interior: at least the outer core must be molten.[^margot2007]

Mariner 10 detected a global magnetic field in 1974, roughly one per cent as strong at the
surface as Earth's and generated by a dynamo in the liquid outer core; its dipole sits north
of the planet's equator.[^nasamessenger]

## Surface

Mercury superficially resembles the Moon: a dark, heavily cratered crust with no water and no
weather to erase impacts. The largest structure is the Caloris basin, about 1,550 kilometres
across, formed near the end of the era of heavy bombardment; the terrain directly opposite it
on the globe is broken into hills and lineations by the shock. Smooth plains of volcanic
origin cover large areas of the northern hemisphere.

Mercury's distinctive landform is the lobate scarp, a curving cliff produced where the crust
was thrust over itself as the planet cooled and contracted. A survey of more than 5,900 such
features in MESSENGER images implied a decrease in the planet's radius of as much as seven
kilometres, far more than the 0.8 to 3 kilometres inferred from Mariner 10 coverage, and
enough to reconcile the geology with thermal models of a large cooling core.[^byrne2014]
MESSENGER also found surface rocks rich in sulfur and poor in iron, indicating that the planet
assembled under chemically reducing conditions.[^nasamessenger]

With no atmosphere to move heat around, surface temperatures span the widest range of any
planet, from about 700 kelvin at the subsolar point near perihelion to roughly 100 kelvin on
the night side.[^nasafacts]

## Polar deposits

Radar observations in August 1991, with the Goldstone 70-metre antenna transmitting and the
Very Large Array receiving, revealed unusually bright patches near Mercury's north pole,
located where permanently shadowed crater floors would be.[^slade1992] Because the axial tilt
is near zero, such floors stay permanently cold. MESSENGER's neutron spectrometer later
measured a deficit of epithermal neutrons over the north polar region, best matched by a
buried layer of nearly pure water ice beneath a thin, darker covering, probably delivered by
comets and volatile-rich asteroids.[^lawrence2013]

## Observation and exploration

Mercury has been recorded since antiquity and is best seen low in twilight; during the
darkness of a total [[Solar eclipse|solar eclipse]] it can occasionally be photographed close
beside the Sun. Like Venus it shows a full cycle of phases, first reported by Giovanni Zupi in
1639 — three decades after the phases of Venus had told against an Earth-centred cosmos in
[[The Copernican Revolution|the Copernican revolution]]. The planet transits the Sun's disc
about thirteen times a century, always in May or November; the transit of 11 November 2019
will be followed by one on 13 November 2032.

Mariner 10 made three flybys in 1974 and 1975 and imaged about 45 per cent of the surface.
MESSENGER, launched on 3 August 2004, became the first spacecraft to orbit Mercury on 18 March
2011 and was deliberately crashed into the surface on 30 April 2015 when its propellant ran
out.[^nasamessenger] BepiColombo, a joint European and Japanese mission carrying two orbiters,
launched on 20 October 2018 and is scheduled to enter Mercury orbit on 21 November 2026, a
year later than first planned after a fault reduced the thrust of its transfer
module.[^esabepi]
""",
        "tier": "standard",
        "kind": "place",
        "infobox": {
            "title": "Mercury",
            "subtitle": "Innermost planet of the Solar System",
            "rows": [
                {"kind": "header", "value": "Physical characteristics"},
                {"kind": "row", "label": "Equatorial radius", "value": "2,440 km (0.383 Earth)"},
                {"kind": "row", "label": "Mass", "value": "3.301 × 10²³ kg (0.055 Earth)"},
                {"kind": "row", "label": "Mean density", "value": "5,429 kg/m³"},
                {"kind": "row", "label": "Surface gravity", "value": "3.70 m/s²"},
                {"kind": "row", "label": "Surface temperature", "value": "about 100 K to 700 K"},
                {"kind": "row", "label": "Natural satellites", "value": "None"},
                {"kind": "header", "value": "Orbit and rotation"},
                {
                    "kind": "row",
                    "label": "Semi-major axis",
                    "value": "57.909 million km (0.387 AU)",
                },
                {"kind": "row", "label": "Orbital period", "value": "87.969 days"},
                {"kind": "row", "label": "Eccentricity", "value": "0.2056"},
                {"kind": "row", "label": "Rotation period", "value": "58.646 days"},
                {"kind": "row", "label": "Axial tilt", "value": "0.034°"},
                {"kind": "header", "value": "Exploration"},
                {
                    "kind": "row",
                    "label": "Spacecraft",
                    "value": "Mariner 10 (1974–1975), MESSENGER (2008–2015)",
                },
                {
                    "kind": "full",
                    "value": (
                        "Named after the Roman messenger god, as is the element "
                        "[[Mercury (element)|mercury]]."
                    ),
                },
            ],
        },
        "image": {
            "url": (
                "https://upload.wikimedia.org/wikipedia/commons/3/30/"
                "Mercury_in_color_-_Prockter07_centered.jpg"
            ),
            "alt": "Globe of Mercury, its grey surface crowded with overlapping impact craters",
            "caption": "Mercury imaged by the MESSENGER spacecraft during its first flyby",
            "credit": (
                "NASA / Johns Hopkins University Applied Physics Laboratory / "
                "Carnegie Institution of Washington"
            ),
            "license": "Public domain",
            "source_url": (
                "https://commons.wikimedia.org/wiki/"
                "File:Mercury_in_color_-_Prockter07_centered.jpg"
            ),
        },
        "references": [
            {
                "key": "nasafacts",
                "title": "Mercury Fact Sheet",
                "url": "https://nssdc.gsfc.nasa.gov/planetary/factsheet/mercuryfact.html",
                "authors": "",
                "publisher": "NASA Space Science Data Coordinated Archive",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
            {
                "key": "smith2012",
                "title": "Gravity Field and Internal Structure of Mercury from MESSENGER",
                "url": "https://pubmed.ncbi.nlm.nih.gov/22438509/",
                "authors": "David E. Smith, Maria T. Zuber and others",
                "publisher": "Science",
                "published_on": "2012",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1126/science.1218809",
                "quote": "",
            },
            {
                "key": "margot2007",
                "title": "Large Longitude Libration of Mercury Reveals a Molten Core",
                "url": "https://pubmed.ncbi.nlm.nih.gov/17478713/",
                "authors": "Jean-Luc Margot, Stanton J. Peale and others",
                "publisher": "Science",
                "published_on": "2007",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1126/science.1140514",
                "quote": "",
            },
            {
                "key": "pettengill1965",
                "title": "A Radar Determination of the Rotation of the Planet Mercury",
                "url": "https://www.nature.com/articles/2061240a0",
                "authors": "Gordon H. Pettengill and Rolf B. Dyce",
                "publisher": "Nature",
                "published_on": "1965",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1038/2061240a0",
                "quote": "",
            },
            {
                "key": "correia2004",
                "title": (
                    "Mercury's capture into the 3/2 spin-orbit resonance as a result of its "
                    "chaotic dynamics"
                ),
                "url": "https://www.nature.com/articles/nature02609",
                "authors": "Alexandre C. M. Correia and Jacques Laskar",
                "publisher": "Nature",
                "published_on": "2004",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1038/nature02609",
                "quote": "",
            },
            {
                "key": "will2014",
                "title": "The Confrontation between General Relativity and Experiment",
                "url": "https://link.springer.com/article/10.12942/lrr-2014-4",
                "authors": "Clifford M. Will",
                "publisher": "Living Reviews in Relativity",
                "published_on": "2014",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.12942/lrr-2014-4",
                "quote": "",
            },
            {
                "key": "byrne2014",
                "title": "Mercury's global contraction much greater than earlier estimates",
                "url": "https://www.nature.com/articles/ngeo2097",
                "authors": "Paul K. Byrne, Christian Klimczak and others",
                "publisher": "Nature Geoscience",
                "published_on": "2014",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1038/ngeo2097",
                "quote": "",
            },
            {
                "key": "slade1992",
                "title": "Mercury Radar Imaging: Evidence for Polar Ice",
                "url": "https://pubmed.ncbi.nlm.nih.gov/17748898/",
                "authors": "Martin A. Slade, Bryan J. Butler and Duane O. Muhleman",
                "publisher": "Science",
                "published_on": "1992",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1126/science.258.5082.635",
                "quote": "",
            },
            {
                "key": "lawrence2013",
                "title": (
                    "Evidence for Water Ice Near Mercury's North Pole from MESSENGER Neutron "
                    "Spectrometer Measurements"
                ),
                "url": "https://pubmed.ncbi.nlm.nih.gov/23196909/",
                "authors": "David J. Lawrence and others",
                "publisher": "Science",
                "published_on": "2013",
                "accessed_on": "2026-09-26",
                "identifier": "doi:10.1126/science.1229953",
                "quote": "",
            },
            {
                "key": "nasamessenger",
                "title": "MESSENGER",
                "url": "https://science.nasa.gov/mission/messenger/",
                "authors": "",
                "publisher": "NASA Science",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
            {
                "key": "esabepi",
                "title": "BepiColombo",
                "url": "https://www.esa.int/Science_Exploration/Space_Science/BepiColombo",
                "authors": "",
                "publisher": "European Space Agency",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
        ],
        "see_also": [
            "The Solar System",
            "General relativity",
            "Mercury (element)",
            "Solar eclipse",
            "The Copernican Revolution",
        ],
        "aliases": [],
        "is_stub": False,
        "is_disambiguation": False,
        "tags": [
            "planet",
            "spin-orbit resonance",
            "MESSENGER",
            "planetary science",
            "perihelion precession",
        ],
    },
    {
        "title": "Mercury",
        "category": "Astronomy and Space",
        "categories": [],
        "short_description": "Disambiguation page for the planet, the element and the Roman god",
        "summary": (
            "Mercury may refer to the innermost planet of the Solar System, to the liquid "
            "metal element of atomic number 80, or to the Roman god of messages and trade "
            "after whom both were named."
        ),
        "content": """**Mercury** may refer to any of several subjects that take their name from a
Roman god.

## Astronomy

* [[Mercury (planet)]] — the smallest planet of [[The Solar System|the Solar System]] and
  the closest to the Sun, which it orbits in 88 days.

## Chemistry

* [[Mercury (element)]] — chemical element 80, the only metal that is liquid at ordinary
  room temperature, known for centuries as quicksilver and central to the practice of
  [[Alchemy|alchemy]].

## Religion and myth

* Mercury, the Roman god of messages, commerce and travellers, identified with the Greek
  Hermes and worshipped across [[The Roman Empire|the Roman Empire]].[^britannicagod]

## Origin of the shared name

The god's name is usually connected with the Latin *merx*, meaning merchandise. The planet
was named for him because it moves faster against the stars than any other, and the metal
because it runs and scatters rather than holding a shape. Alchemical practice reinforced the
pairing by using one symbol for both the planet and the metal.
""",
        "tier": "stub",
        "kind": "disambiguation",
        "infobox": None,
        "image": None,
        "references": [
            {
                "key": "britannicagod",
                "title": "Mercury: Roman god",
                "url": "https://www.britannica.com/topic/Mercury-Roman-god",
                "authors": "",
                "publisher": "Encyclopaedia Britannica",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
        ],
        "see_also": [
            "Mercury (planet)",
            "Mercury (element)",
            "Alchemy",
            "The Roman Empire",
        ],
        "aliases": [],
        "is_stub": True,
        "is_disambiguation": True,
        "tags": ["disambiguation", "naming"],
    },
    {
        "title": "The Copernican Revolution",
        "category": "Astronomy and Space",
        "categories": ["History", "Physics"],
        "short_description": "The long shift from an Earth-centred to a Sun-centred astronomy",
        "summary": (
            "The Copernican Revolution was the transformation of European astronomy between "
            "the publication of Copernicus's De revolutionibus in 1543 and Newton's "
            "Principia in 1687, which put the Sun rather than the Earth at the centre."
        ),
        "content": """**The Copernican Revolution** was the transformation of European astronomy and
cosmology that began with the publication of Nicolaus Copernicus's *De revolutionibus orbium
coelestium* in 1543 and acquired a physical explanation in Isaac Newton's *Principia* of
1687. It replaced a universe in which the Sun, Moon and planets circled a motionless Earth
with one in which the Earth is itself a planet, turning daily on its axis and travelling
annually around the Sun.[^sepcopernicus] The change took roughly 150 years, and for most of
that time the new arrangement was neither more accurate nor more economical than the old
one. For the several other meanings of the word, see [[Revolution]].

## The system it replaced

Ptolemy's *Almagest*, compiled in Alexandria in the second century, modelled each planet as
a point moving on a small circle, the epicycle, whose centre travelled on a larger circle
around a near-central Earth. Additional devices, notably the equant, were needed to
reproduce the observed variation in speed. The scheme worked: it predicted planetary
positions well enough for calendars and horoscopes, although errors of a few degrees
accumulated over long intervals. It also came embedded in Aristotelian physics, in which
heavy bodies fall toward the centre of the universe and the heavens are made of an
unchanging fifth element.

Astronomers of [[The Islamic Golden Age|the Islamic Golden Age]] had already criticised the
equant as a violation of strictly uniform circular motion, and devised alternative
constructions — the best known being the Tusi couple of Nasir al-Din al-Tusi in the
thirteenth century, a pair of nested circles that generates straight-line oscillation.
Copernicus used the same device. A moving Earth had been proposed in antiquity by Aristarchus
of Samos, and rejected, largely because no annual shift in the apparent positions of the
stars could be detected and because a spinning Earth seemed physically absurd.

## De revolutionibus

Copernicus (1473–1543) was a canon of the cathedral chapter of Warmia, in Royal Prussia, and
an astronomer in the time left over from administration and medicine. He sketched his system
in an unpublished manuscript, the *Commentariolus*, around 1514, which ends with the claim
that thirty-four circles are enough to account for the whole motion of the planets. The
finished work, in six books, was printed in Nuremberg by Johannes Petreius in 1543, the year
Copernicus died; his student Georg Joachim Rheticus had arranged the printing. The Lutheran
theologian Andreas Osiander, who took over supervision of the press, added an unsigned
preface presenting the scheme as a calculating convenience rather than a description of the
world — against the author's evident intent.[^sepcopernicus]

The model kept perfectly circular orbits and still needed epicycles, and it was not
noticeably more accurate than Ptolemy's. Its advantages were structural. The retrograde
loops that planets appear to trace resolved into a consequence of viewing them from a moving
Earth. More decisively, the order of the planets and the relative sizes of their orbits were
now fixed by the model rather than chosen freely: Copernicus placed [[Mercury (planet)|Mercury]]
innermost at 0.376 of the Earth–Sun distance, close to the modern 0.387, and derived
comparable values for the rest of [[The Solar System|the Solar System]].[^kuhn1957]

## Reception

Acceptance was slow and selective. Erasmus Reinhold's *Prutenic Tables* of 1551 adopted
Copernicus's parameters while ignoring his cosmology, which was possible because the
mathematics could be used without believing the Earth moved. The survey by Owen Gingerich of
some 600 surviving copies of the first two editions found them heavily annotated by working
astronomers, contradicting Arthur Koestler's description of *De revolutionibus* as the book
nobody read.[^gingerich2004]

Tycho Brahe (1546–1601) refused a moving Earth but produced pre-telescopic observations
accurate to about an arcminute, and proposed a compromise in which the planets orbit the Sun
while the Sun orbits a stationary Earth. On the Catholic side, the Congregation of the Index
suspended *De revolutionibus* in 1616 pending correction; a lightly censored text appeared in
1620, and the work was not removed from the Index until 1835.[^sepgalileo]

## Kepler and Galileo

Johannes Kepler (1571–1630) inherited Tycho's observations of Mars. A residual discrepancy
of eight arcminutes, which he declined to dismiss, drove him to abandon circles altogether.
*Astronomia nova* (1609) states that a planet moves on an ellipse with the Sun at one focus,
and that the line from Sun to planet sweeps equal areas in equal times; *Harmonices mundi*
(1619) adds that the square of the orbital period is proportional to the cube of the mean
distance.[^sepkepler] His *Rudolphine Tables* of 1627 were markedly more accurate than any
predecessor, which was the first practical argument in the new system's favour.

[[Galileo Galilei]] removed several objections with the telescope between 1609 and 1613.
Mountains on the Moon and spots on the Sun told against the perfection of the heavens; four
satellites circling Jupiter showed that the Earth was not the sole centre of motion; and the
complete cycle of phases shown by Venus was incompatible with the Ptolemaic
arrangement.[^sepgalileo] His *Dialogue Concerning the Two Chief World Systems* (1632) led to
his trial in 1633 and to house arrest for the remaining nine years of his life.

## Newton and the physical case

What remained was the physics. Nothing in Kepler's laws explained why a planet keeps moving,
or why a rotating Earth does not shed its oceans and inhabitants. [[Isaac Newton]] supplied
the missing account in *Philosophiæ Naturalis Principia Mathematica* (1687), deriving all
three of Kepler's laws from three laws of motion together with a single inverse-square
attraction acting between every pair of masses.[^kuhn1957] Direct observational proof of the
Earth's motion arrived later still: James Bradley announced the aberration of starlight in
1729, and Friedrich Bessel measured the first stellar parallax, for the star 61 Cygni, in
1838.

## The idea of a revolution

The episode supplied the title of Thomas Kuhn's 1957 study, which treated it as the model
case of a wholesale change in a scientific world-view, and as one component of the broader
episode conventionally called [[The Scientific Revolution]].[^kuhn1957] Historians since have
stressed how gradual, technical and uneven the process was, and how much it owed to the
recovery of ancient texts during
[[The Renaissance|the Renaissance]] and to the cheap, identical copies made possible by
[[The printing press|movable type]].
""",
        "tier": "standard",
        "kind": "period",
        "infobox": {
            "title": "The Copernican Revolution",
            "subtitle": "Change in European cosmology, 1543–1687",
            "rows": [
                {"kind": "row", "label": "Period", "value": "1543 to 1687"},
                {"kind": "row", "label": "Region", "value": "Europe"},
                {"kind": "header", "value": "Landmark works"},
                {"kind": "row", "label": "1543", "value": "Copernicus, *De revolutionibus*"},
                {"kind": "row", "label": "1609", "value": "Kepler, *Astronomia nova*"},
                {"kind": "row", "label": "1610", "value": "Galileo, *Sidereus nuncius*"},
                {"kind": "row", "label": "1619", "value": "Kepler, *Harmonices mundi*"},
                {"kind": "row", "label": "1632", "value": "Galileo, *Dialogue*"},
                {"kind": "row", "label": "1687", "value": "Newton, *Principia*"},
                {"kind": "header", "value": "Later confirmations"},
                {"kind": "row", "label": "1729", "value": "Aberration of starlight (Bradley)"},
                {"kind": "row", "label": "1838", "value": "First stellar parallax (Bessel)"},
                {
                    "kind": "full",
                    "value": (
                        "The label follows Thomas Kuhn's 1957 study; for other senses of the "
                        "word see [[Revolution]]."
                    ),
                },
            ],
        },
        "image": {
            "url": (
                "https://upload.wikimedia.org/wikipedia/commons/2/28/"
                "Copernican_heliocentrism_diagram-2.jpg"
            ),
            "alt": (
                "Woodcut of concentric circles labelled in Latin with the Sun at the centre, "
                "from a printed book of 1543"
            ),
            "caption": (
                "The heliocentric diagram from the first edition of De revolutionibus orbium "
                "coelestium, 1543"
            ),
            "credit": "Nicolaus Copernicus, De revolutionibus orbium coelestium (1543)",
            "license": "Public domain",
            "source_url": (
                "https://commons.wikimedia.org/wiki/"
                "File:Copernican_heliocentrism_diagram-2.jpg"
            ),
        },
        "references": [
            {
                "key": "sepcopernicus",
                "title": "Nicolaus Copernicus",
                "url": "https://plato.stanford.edu/entries/copernicus/",
                "authors": "Sheila Rabin",
                "publisher": "Stanford Encyclopedia of Philosophy",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
            {
                "key": "kuhn1957",
                "title": (
                    "The Copernican Revolution: Planetary Astronomy in the Development of "
                    "Western Thought"
                ),
                "url": "https://www.hup.harvard.edu/books/9780674171039",
                "authors": "Thomas S. Kuhn",
                "publisher": "Harvard University Press",
                "published_on": "1957",
                "accessed_on": "2026-09-26",
                "identifier": "ISBN 0-674-17103-9",
                "quote": "",
            },
            {
                "key": "gingerich2004",
                "title": "The Book Nobody Read: Chasing the Revolutions of Nicolaus Copernicus",
                "url": "https://archive.org/details/booknobodyreadch00ging",
                "authors": "Owen Gingerich",
                "publisher": "Walker & Company",
                "published_on": "2004",
                "accessed_on": "2026-09-26",
                "identifier": "ISBN 0-8027-1415-3",
                "quote": "",
            },
            {
                "key": "sepkepler",
                "title": "Johannes Kepler",
                "url": "https://plato.stanford.edu/entries/kepler/",
                "authors": "",
                "publisher": "Stanford Encyclopedia of Philosophy",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
            {
                "key": "sepgalileo",
                "title": "Galileo Galilei",
                "url": "https://plato.stanford.edu/entries/galileo/",
                "authors": "",
                "publisher": "Stanford Encyclopedia of Philosophy",
                "published_on": "",
                "accessed_on": "2026-09-26",
                "identifier": "",
                "quote": "",
            },
        ],
        "see_also": [
            "Galileo Galilei",
            "Isaac Newton",
            "The Solar System",
            "The Scientific Revolution",
            "Mercury (planet)",
            "The Renaissance",
        ],
        "aliases": ["Heliocentrism"],
        "is_stub": False,
        "is_disambiguation": False,
        "tags": [
            "heliocentrism",
            "Copernicus",
            "Kepler",
            "history of astronomy",
            "cosmology",
        ],
    },
]
